name: ci

on:
  push:
    # branches: [telekom-msk-eu-devops]
env:
  APP: msk
  GEO: eu
  ENV: devops

jobs:
  pipeline:
    runs-on: ['test']
    services:
      redis:
        image: redis:5-alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: kaia_api_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: "elgohr/asdf-build-action@master"
        env: 
          ENVIRONMENT: "golang"
          VERSION: "1.12"
        args: "go test ./..."

